# Generated by Django 4.2.19 on 2025-03-07 03:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_event_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="seating_emoji",
            field=models.BooleanField(default=False, verbose_name="🪑"),
        ),
        migrations.AddField(
            model_name="venue",
            name="seating_information",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
