# Generated by Django 4.2.19 on 2025-03-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_venue_seating_emoji_venue_seating_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="piano_emoji",
            field=models.BooleanField(default=False, verbose_name="🎹"),
        ),
        migrations.AddField(
            model_name="venue",
            name="piano_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
